services:
  - type: web
    name: delta-restaurant-front-end
    runtime: static
    buildCommand: 'npm install && npm run build'
    startCommand: 'npm run dev'
    envVars:
      - key: PORT
        value: 5000
    autoDeploy: true

  - type: web
    name: delta-restaurant-back-end
    runtime: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm run server'
    envVars:
      - key: DATA_PATH
        value: ./data/data.json
      - key: RESERVATIONS_PATH
        value: ./data/reservations.json
      - key: COMMANDES_PATH
        value: ./data/commandes.json
      - key: CONTACTS_PATH
        value: ./data/contacts.json
      - key: DB_PATH
        value: ./database.db
      - key: PORT
        value: 5000
    autoDeploy: true
